'use client'

import type { LucideIcon } from 'lucide-react'
import type { CSSProperties, HTMLAttributes, ReactElement, ReactNode } from 'react'
import { isValidElement, useEffect, useRef, useState } from 'react'

import { StatusIndicator, type StatusVariant } from '@/components/ui/utils/status-indicator'
import { cn } from '@/lib/utils'

// The bounds a canvas node is drawn within.
//
// Exported deliberately, and this is the reason this component is in the kit at
// all: a canvas node element has no width or height of its own -- it is sized
// by whatever it renders, between these two numbers. Anything that has to stand
// in for a node before the node exists (the loading placeholder above all) has
// to know them, and the only alternative to exporting them is the host copying
// them in by hand, where nothing fails when the shell later changes.
//
// Plain numbers rather than Tailwind classes on purpose: `min-w-[200px]` is an
// arbitrary value, which the live preview never generates, and 200 is not a
// value on the spacing scale. An inline width is the one spelling that renders
// the same here and in an app build.
export const NODE_CARD_MIN_WIDTH = 200
export const NODE_CARD_MAX_WIDTH = 240

// A node is dimmed unless it is selected. Exported for the same reason as the
// widths: anything drawn in a node's place has to match it, and a copied value
// is one nobody updates. The classes are written as literals here so the
// scanner sees them -- a class name assembled at runtime is generated by
// nothing and would silently produce no filter at all.
export function nodeCardBrightness(selected?: boolean): string {
  return selected ? 'brightness-100' : 'brightness-90'
}

export interface NodeCardProps extends Omit<HTMLAttributes<HTMLDivElement>, 'className' | 'style'> {
  children: ReactNode
  selected?: boolean
  loading?: boolean
  /** A CSS colour for the node's type accent, e.g. `var(--primary)`. */
  accent?: string
  error?: boolean
  className?: string
}

// The dots that travel around the border while a node is working. The keyframes
// ride along in a <style> element rather than a stylesheet: a design-kit
// component ships source files only, so an imported .css would be dropped on
// install and silently do nothing. Only a loading node renders this, so the
// duplicate declarations are few and cost nothing -- identical rules collapse.
function TravelingDot({
  accent,
  dots = 8,
  dotSize = 4,
  className,
}: {
  accent: string
  dots?: number
  dotSize?: number
  className?: string
}) {
  const ref = useRef<HTMLDivElement>(null)
  const [size, setSize] = useState({ w: 0, h: 0 })

  useEffect(() => {
    if (!ref.current) {
      return
    }
    const obs = new ResizeObserver(([entry]) => {
      const rect = entry.target.getBoundingClientRect()
      setSize({ w: Math.round(rect.width), h: Math.round(rect.height) })
    })
    obs.observe(ref.current)
    return () => obs.disconnect()
  }, [])

  if (!size.w || !size.h) {
    return <div ref={ref} className='absolute inset-0 pointer-events-none' />
  }

  const r = 6

  return (
    <div ref={ref} className={cn('absolute inset-0 pointer-events-none overflow-visible', className)}>
      <style>{'@keyframes node-card-dot-travel{from{stroke-dashoffset:0}to{stroke-dashoffset:-100}}'}</style>
      <svg width={size.w} height={size.h} className='overflow-visible'>
        {Array.from({ length: dots }, (_, i) => {
          const delay = -(i * (4 / dots))
          return (
            <rect
              key={i}
              x='0.5'
              y='0.5'
              width={size.w - 1}
              height={size.h - 1}
              rx={r}
              ry={r}
              fill='none'
              stroke={accent}
              strokeWidth='1'
              pathLength='100'
              strokeDasharray={`${dotSize} ${100 - dotSize}`}
              style={{ animation: `node-card-dot-travel 4s linear infinite`, animationDelay: `${delay}s` }}
            />
          )
        })}
      </svg>
    </div>
  )
}

export function NodeCard({ children, selected, loading, accent, error, className, ...rest }: NodeCardProps) {
  const lineAccent = error ? 'var(--destructive)' : accent
  const showRing = error || ((loading || selected) && accent)
  const ringColor = error
    ? 'var(--destructive)'
    : accent
      ? `color-mix(in oklch, ${accent} 20%, transparent)`
      : undefined
  return (
    <div
      className={cn(
        'relative rounded-md p-px',
        'shadow-lg shadow-black/50 bg-card',
        nodeCardBrightness(selected),
        showRing && 'ring-1 ring-inset',
        className,
      )}
      style={{
        minWidth: NODE_CARD_MIN_WIDTH,
        ...(showRing && ringColor ? ({ '--tw-ring-color': ringColor } as CSSProperties) : null),
      }}
      {...rest}
    >
      {lineAccent && (
        <>
          <div
            className={cn('absolute top-0 left-1 right-1 h-px', selected ? 'opacity' : 'opacity-50')}
            style={{ background: `linear-gradient(90deg, transparent 10%, ${lineAccent} 70%, transparent)` }}
          />
          <div
            className={cn('absolute bottom-0 left-1 right-1 h-px', selected ? 'opacity-50' : 'opacity-10')}
            style={{ background: `linear-gradient(90deg, transparent, ${lineAccent} 30%, transparent 90%)` }}
          />
        </>
      )}
      {loading && accent && !error && <TravelingDot accent={accent} className={'opacity-20'} />}
      {children}
    </div>
  )
}

export interface NodeCardHeaderProps {
  /** The node type's icon component -- or an element, for the case where there
   * is no icon to draw yet. The loading placeholder passes a skeleton bar here
   * rather than rebuilding this row, which is what keeps the two headers on one
   * set of spacing instead of two that have to be kept in step. */
  icon: LucideIcon | ReactElement
  /** Applies to an icon component; an element passed in styles itself. */
  iconClassName?: string
  status?: StatusVariant
  title: string
  titleClassName?: string
  subtitle?: string
  extra?: ReactNode
  /** Slots for the host's edge handles -- the kit draws no connection points. */
  input?: ReactNode
  output?: ReactNode
  className?: string
}

export function NodeCardHeader({
  icon,
  iconClassName,
  status,
  title,
  titleClassName,
  subtitle,
  extra,
  input,
  output,
  className,
}: NodeCardHeaderProps) {
  return (
    <div className={cn('flex items-center gap-2 px-4 py-2', className)}>
      {input}
      <div className='relative shrink-0'>
        <NodeCardIcon icon={icon} iconClassName={iconClassName} />
        {status && <StatusIndicator variant={status} className='absolute -bottom-0.5 -right-0.5' />}
      </div>
      <div className='flex flex-col min-w-0'>
        <span className={cn('text font-medium truncate', titleClassName)}>{title}</span>
        {/* 10px is off the type scale, so it is an inline size rather than an
            arbitrary Tailwind value the preview would never generate. */}
        {subtitle && (
          <span className='font-mono text-muted-foreground truncate' style={{ fontSize: 10 }}>
            {subtitle}
          </span>
        )}
      </div>
      <div className='flex-1 flex items-center min-w-0 justify-end'>{extra}</div>
      {output}
    </div>
  )
}

// A lucide icon is a forwardRef object rather than a function, so the two cases
// are told apart by asking whether this is already an element -- not by typeof.
function NodeCardIcon({ icon, iconClassName }: { icon: LucideIcon | ReactElement; iconClassName?: string }) {
  if (isValidElement(icon)) {
    return icon
  }
  const Icon = icon as LucideIcon
  return <Icon className={cn('h-4 w-4', iconClassName)} />
}

export function NodeCardContent({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <div className={cn('px-4 pb-3', className)}>
      {/* An inline gradient for the same reason as the subtitle: `via-white/[0.06]`
          is an arbitrary opacity and would not render in the preview. */}
      <div
        className='h-px mb-2'
        style={{
          background: 'linear-gradient(to right, transparent, rgba(255,255,255,0.06), transparent)',
        }}
      />
      {children}
    </div>
  )
}
